<?php require TEMPLATES . '/includes/cabecalho.phtml' ?>
<h1>Criar Produtos</h1>
<form action="">
    <div>
        <label>Nome Completo</label>
        <input type="text" name="nome" id="name" placeholder="Seu Nome Completo">
    </div>
    <div>
        <label>Descrição</label>
        <input type="text" name="descricao" id="descricao" placeholder="Descrição do Produto">
    </div>
    <div>
        <label>Sobre</label>
        <textarea name="sobre" id="sobre" placeholder="Sobre o Produto">
        </textarea>
    </div>
    <div>
        <label>Valor</label>
        <input type="text" name="valor" id="valor" placeholder="Valor do Produto">
    </div>
</form>
<?php require TEMPLATES . '/includes/rodape.phtml' ?>
