<?php require TEMPLATES . '/includes/cabecalho.phtml' ?>
<h1>Criar Produtos</h1>
<form action="<?php echo HOME;?>?pagina=/produto/salvar" method="post">
    <div>
        <label>Nome Completo</label>
        <input type="text" name="nome" id="name" placeholder="Seu Nome Completo">
    </div>
    <div>
        <label>Descrição</label>
        <input type="text" name="descricao" id="descricao" placeholder="Descrição do Produto">
    </div>
    <div>
        <label>Sobre</label>
        <textarea name="sobre" id="sobre" placeholder="Sobre o Produto">
        </textarea>
    </div>
    <div>
        <label>Valor</label>
        <input type="text" name="valor" id="valor" placeholder="Valor do Produto">
    </div>

    <div>
        <label>Status</label>
        <input type="number" name="quantidade" id="quantidade" placeholder="Quantidade Estoque do produto...">
    </div>
    <div>
        <label>Quantidade Estoque</label>
        <select name="status" id="status">
            <option value="1">Ativo</option>
            <option value="2">Inativo</option>
        </select>
    </div>

    <button>Enviar Produto</button>

</form>
<?php require TEMPLATES . '/includes/rodape.phtml' ?>
