<?php require TEMPLATES . '/includes/cabecalho.phtml' ?>
<h1>Criar Produtos</h1>
<form action="<?php echo HOME;?>?pagina=/produtos/salvar" method="post" enctype="multipart/form-data">
    <div class="form-group mb-3">
        <label>Nome Completo</label>
        <input class="form-control"  type="text" name="nome" id="nome" placeholder="Seu Nome Completo">
    </div>
    <div class="form-group mb-3">
        <label>Descrição</label>
        <input class="form-control" type="text" name="descricao" id="descricao" placeholder="Descrição do Produto">
    </div>
    <div class="form-group mb-3">
        <label>Sobre</label>
        <textarea class="form-control"  name="sobre" id="sobre" placeholder="Sobre o Produto">
        </textarea>
    </div>
    <div class="form-group mb-3">
        <label>Valor</label>
        <input class="form-control"  type="text" name="valor" id="valor" placeholder="Valor do Produto">
    </div>

    <div class="form-group mb-3">
        <label>Status</label>
        <input class="form-control" type="number" name="quantidade" id="quantidade" placeholder="Quantidade Estoque do produto...">
    </div>
    <div class="form-group mb-3">
        <label>Quantidade Estoque</label>
        <select class="form-control"  name="status" id="status">
            <option value="1">Ativo</option>
            <option value="2">Inativo</option>
        </select>
    </div>

    <div class="form-group mb-3">
        <label>Fotos Produtos</label>
        <input class="form-control" type="file" name="foto" multiple>
    </div>

    <button class="btn btn-lg btn-success">Enviar Produto</button>

</form>
<?php require TEMPLATES . '/includes/rodape.phtml' ?>
