<?php require TEMPLATES . '/includes/cabecalho.phtml' ?>
<h1>Editar Produtos</h1>
<form action="<?php echo HOME;?>?pagina=/produtos/atualizar&produto=<?= $produto['id'];?>" method="post" enctype="multipart/form-data">
    <div class="form-group mb-3">
        <label>Nome Completo</label>
        <input class="form-control" type="text" name="nome" id="nome" placeholder="Seu Nome Completo" value="<?= $produto['nome'];?>">
    </div>
    <div class="form-group mb-3">
        <label>Descrição</label>
        <input class="form-control" type="text" name="descricao" id="descricao" placeholder="Descrição do Produto"  value="<?= $produto['descricao'];?>">
    </div>
    <div class="form-group mb-3">
        <label>Sobre</label>
        <textarea class="form-control" name="sobre" id="sobre" placeholder="Sobre o Produto">
            <?= $produto['sobre'];?>
        </textarea>
    </div>
    <div class="form-group mb-3">
        <label>Valor</label>
        <input class="form-control" type="text" name="valor" id="valor" placeholder="Valor do Produto"  value="<?= number_format($produto['valor'], 2, ',', '.')?>">
    </div>

    <div class="form-group mb-3">
        <label>Status</label>
        <input class="form-control" type="number" name="quantidade" id="quantidade" placeholder="Quantidade Estoque do produto..."  value="<?= $produto['quantidade'];?>">
    </div>
    <div class="form-group mb-3">
        <label>Status</label>
        <select class="form-control" name="status" id="status">
            <option value="1" <?=$produto['status'] == 1 ? 'selected' : ''?>>Ativo</option>
            <option value="2" <?=$produto['status'] == 2 ? 'selected' : ''?>>Inativo</option>
        </select>
    </div>
    <div class="form-group mb-3">
        <label>Fotos Produtos</label>
        <input class="form-control" type="file" name="foto" multiple>
    </div>

    <button class="btn btn-lg btn-success">Atualizar Produto</button>

</form>
<?php require TEMPLATES . '/includes/rodape.phtml' ?>
