<?php require TEMPLATES . '/includes/cabecalho.phtml' ?>
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h2>Produtos</h2>
        <a class="btn btn-success" href="<?= HOME . '?pagina=/produtos/criar' ?>">Criar Produtos</a>

    </div>
    <div>
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Produto</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($produtos as $produto) : ?>
                <tr>
                    <td><?= $produto['id'] ?></td>
                    <td><?= $produto['nome'] ?></td>
                    <td><a class="btn btn-sm btn-primary"
                           href="<?= HOME ?>/?pagina=/produtos/editar&produto=<?= $produto['id'] ?>">Editar </a>
                        <a class="btn btn-sm btn-danger"
                           href="<?= HOME ?>/?pagina=/produtos/remover&produto=<?= $produto['id'] ?>">Remover </a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php require TEMPLATES . '/includes/rodape.phtml' ?>