<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo isset($titulo) ? $titulo : PROJETO; ?></title>
</head>
<body>
<ul>
    <li><a href="<?= HOME . '?pagina=/produtos'?>">Produtos</a></li>
</ul>